repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      # Run the linter with import sorting.
      - id: ruff-check
        args: [--extend-select=I, --fix]
      # Run the formatter.
      - id: ruff-format
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    # Enforce Conventional Commits style
    -   id: gitlint
        args: [--contrib=contrib-title-conventional-commits,--ignore=body-is-missing, --msg-filename]
-   repo: local
    hooks:
    -   id: pytest on notebooks
        # This hook runs pytest on notebooks using nbmake to ensure that the notebook outputs match the expected outputs.
        name: pytest
        entry: uv run pytest --nbmake
        language: system
        files: \.ipynb$
        pass_filenames: true
